services:
    ernadoo.visitcounterbyforum.event.listener:
        class: ernadoo\visitcounterbyforum\event\listener
        arguments:
            - @user
        tags:
            - { name: event.listener }